#!/usr/bin/env bash
# Writes web/.env.local from the deployed stack's CloudFormation outputs.
set -euo pipefail

STACK="${STACK:-ReelLens}"
REGION="${AWS_REGION:-us-east-1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

outputs=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query 'Stacks[0].Outputs' --output json)

get() { printf '%s' "$outputs" | python3 -c "import json,sys; print(next((o['OutputValue'] for o in json.load(sys.stdin) if o['OutputKey']=='$1'), ''))"; }

cat > "$ROOT/web/.env.local" <<ENV
# Generated by scripts/write-web-env.sh — do not commit.
NEXT_PUBLIC_API_URL=$(get ApiUrl)
NEXT_PUBLIC_USER_POOL_ID=$(get UserPoolId)
NEXT_PUBLIC_USER_POOL_CLIENT_ID=$(get UserPoolClientId)
NEXT_PUBLIC_COGNITO_DOMAIN=$(get HostedUiDomain)
NEXT_PUBLIC_WS_URL=$(get WsUrl)
ENV

echo "wrote $ROOT/web/.env.local"
cat "$ROOT/web/.env.local"
