#!/usr/bin/env bash
# Writes mobile/.env.local from the deployed stack's CloudFormation outputs.
#
# Expo inlines EXPO_PUBLIC_* at bundle time, like NEXT_PUBLIC_* on the web, so
# this runs before `expo start` / `expo run:*`. None of these are secrets: they
# are the same public identifiers the web bundle already ships.
set -euo pipefail

# Defaults to this repo's stack, not the MVP's (see write-web-env.sh).
STACK="${STACK:-ReelLensMultiTenant}"
REGION="${AWS_REGION:-us-east-1}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

outputs=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query 'Stacks[0].Outputs' --output json)

get() { printf '%s' "$outputs" | python3 -c "import json,sys; print(next((o['OutputValue'] for o in json.load(sys.stdin) if o['OutputKey']=='$1'), ''))"; }

cat > "$ROOT/mobile/.env.local" <<ENV
# Generated by scripts/write-mobile-env.sh — do not commit.
EXPO_PUBLIC_API_URL=$(get ApiUrl)
EXPO_PUBLIC_USER_POOL_CLIENT_ID=$(get UserPoolClientId)
EXPO_PUBLIC_COGNITO_DOMAIN=$(get HostedUiDomain)
EXPO_PUBLIC_WS_URL=$(get WsUrl)
ENV

echo "wrote $ROOT/mobile/.env.local"
cat "$ROOT/mobile/.env.local"
